### ISSUE TITLE
`alda update` prompt no longer works

### ISSUE THREAD

**Issue by elydpg** [alda-lang/alda-client-java#35] opened 2018-07-02 07:01 UTC
Attempting to update via the suggested prompt no longer works.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\elyis> alda update
Automated updates to alda.exe are not possible due to limitations of the Windows OS.
For more information, see: https://github.com/alda-lang/alda-client-java/issues/24

To update alda.exe, first, make sure that the server is not up by running:

   alda down

Then, run the following command in your terminal to download the latest alda.exe:

    powershell -Command Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"

Or, if you'd prefer, you can install the latest alda.exe yourself from:
https://github.com/alda-lang/alda/releases

PS C:\Users\elyis> alda down
[27713] Server already down.
PS C:\Users\elyis> powershell -Command Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/downlo
ad/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:123
+ ... s/download/1.0.0-rc82/alda.exe -OutFile C:\Program Files (x86)\Alda\a ...
+                                                               ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\elyis> Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.e
xe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/do ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]
   , WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
   and

PS C:\Users\elyis> Invoke-WebRequest -Uri "http://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.ex
e" -OutFile "C:\Program Files (x86)\Alda\alda.exe"
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri "http://github.com/alda-lang/alda/releases/dow ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]
   , WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
   and

PS C:\Users\elyis> cd "C:\Program Files (x86)\Alda"
PS C:\Program Files (x86)\Alda> powershell -Command Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/re
leases/download/1.0.0-rc82/alda.exe" -OutFile "alda.exe"
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri https://github.com/alda-lang/alda/releases/dow ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]
   , WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
   and

PS C:\Program Files (x86)\Alda> powershell -Command Invoke-WebRequest -Uri "http://github.com/alda-lang/alda/rel
eases/download/1.0.0-rc82/alda.exe" -OutFile "alda.exe"
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest -Uri http://github.com/alda-lang/alda/releases/down ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]
   , WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
   and

PS C:\Program Files (x86)\Alda>
```

**Comment by elydpg** [comment] 2018-07-02 07:31
If the text wall is too hard to read, here's an image version:

![shell_output](https://user-images.githubusercontent.com/8622264/42150635-1fca2de8-7de3-11e8-8902-3e1d01e862cc.png)

**Comment by jgkamat** [comment] 2018-07-02 09:44
elyisgreat writes:

> PS C:\Users\elyis> powershell -Command Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/downlo
> ad/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"
> x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:123
> + ... s/download/1.0.0-rc82/alda.exe -OutFile C:\Program Files (x86)\Alda\a ...
> +                                                               ~~~
>     + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

This is a very weird error, I wonder why it's throwing a command not found
error for text inside a string. This is probably some feature or parsing
behaivor of PowerShell that I'm overlooking. I'm guessing this is related to
having the 'x86' in parens. Maybe single quoting would be better (as it is in
bash).

> Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
> At line:1 char:1
> + Invoke-WebRequest -Uri "http://github.com/alda-lang/alda/releases/dow ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]
>    , WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
>    and

My best guess for this is something wrong with the certificates on your
system.

This could also be a change to the 'Invoke-WebRequest' command syntax though
or something else.

I don't have access to any windows machines anymore, so I'm unable to help
debug this...

If you can find a working command, it should be easy to update the prompt to
print out something that works.

**Comment by TBuc** [comment] 2018-07-02 10:14
Hi @elyisgreat ,

I agree with @jgkamat.  I was already looking at the reported issue (actually, two sub-issues are present), and I've found that the first sub-issue (x86) is avoidable trough single quoting, as per @jgkamat's suggestion, but also needs the command to be embraced in graph brackets. This the working version:
`powershell -Command {Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.exe" -OutFile 'C:\Program Files (x86)\Alda\alda.exe'}`

For what concerns the certificate error, you need to ensure you have _Tls12_ listed in _[Net.ServicePointManager]::SecurityProtocol_, which defines the cryptography protocols allowed by your client. From PowerShell, run:
```
PS C:\Users\myusr> [Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls
```
This is my real output: as you can see, I had no Tls version 1.2 enabled, thus I got your very same error. 

My Powershell details:

```
PS C:\Users\myusr> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  112
```

You can solve it just by adding _Tls12_ value to that list. To do so, you'll need to assign to the SecurityProtocol variable a list consisting of its current values plus the new one(s) you want to add. So, in my case:
```
[Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Ssl3 -bor [System.Net.SecurityProtocolType]::Tls -bor [System.Net.SecurityProtocolType]::Tls12
```
Then check the list is correct (must contain previous values + Tls12):
```
PS C:\Users\myusr> [Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls, Tls12
```
I was looking for a way to just append to the current list, without needing to fully re-definite it by adding again its current values too, but didn't succeed. If someone has better luck at this please drop a line.

**Quick recap**
So the problem is solvable by applying single quotes to the -Output parameter and embracing the passed command in graph brackets, plus enabling Tls12 on your system.

**Comment by elydpg** [comment] 2018-07-02 11:01
The single quotes does not affect the initial error with the `(x86)` file name, however the braces do allow the command to work properly. Nonetheless, I am still getting the same error even after enabling Tls12:

![shell_output](https://user-images.githubusercontent.com/8622264/42160585-73dbdcca-7e00-11e8-9d84-d5dc166161d5.png)

**Comment by TBuc** [comment] 2018-07-02 12:23
Oh yes, sorry: the single quotes are actually not needed (even thought they are more proper in this case since there's no variable to evaluate).

I've just noted that the changes to SecurityProtocol are **only session-scoped** and **not permanent**. Thus, you'll need to invoke the command from the very same PowerShell session where you've modified SecurityProtocol. So, recapping:

1. Launch PowerShell
2. Update SecurityProtocol as per my previous post.
3. Run the command as follows: 
`Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.exe" -OutFile 'C:\Program Files (x86)\Alda\alda.exe'`

HTH

**Comment by elydpg** [comment] 2018-07-02 12:41
I noticed that. My above photo depicts a single session. 

Interestingly, after updating the SecurityProtocol, running

`powershell -Command {Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/downl
oad/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"}`

creates an error, but running

`Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"`

works normally.

**Comment by TBuc** [comment] 2018-07-02 12:52
Exactly: invoking _powershell -Command_ creates a separate session with its own context, whose lifetime boundaries are defined by the execution of the given command, and is not even needed in this case since we're directly executing from the PowerShell environment.

Unfortunately, I can't help users experiencing this issue from cmd.exe (you will need to launch a powershell to issue such update command). In case a user can't use Powershell, he/she will need to manually download the file, then autonomously replace the existing one in their Alda directory.

**Comment by daveyarwood** [comment] 2018-07-02 15:15
Maybe it would make sense for the Alda CLI to provide two separate commands that Windows users can run, depending on if they're using cmd.exe or PowerShell?

**Comment by elydpg** [comment] 2018-07-02 21:15
`powershell -Command {[Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Ssl3 -bor [System.Net.SecurityProtocolType]::Tls -bor [System.Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/1.0.0-rc82/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"}`

works as a one-liner for me! Unfortunately, it seems to work only in instances of PowerShell and not in cmd.exe (Of course this is all assuming the server is already down).

**Comment by elydpg** [comment] 2018-12-03 18:42
Can we update the Windows update prompt so that it says 

```
Automated updates to alda.exe are not possible due to limitations of the Windows OS.
For more information, see: https://github.com/alda-lang/alda-client-java/issues/24

To update alda.exe, first, make sure that the server is not up by running:

   alda down

Then, run the following command in your terminal to download the latest alda.exe:

    powershell -Command {[Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Ssl3 -bor [System.Net.SecurityProtocolType]::Tls -bor [System.Net.SecurityProtocolType]::Tls12 ; Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/<version>/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"}

Or, if you'd prefer, you can install the latest alda.exe yourself from:
https://github.com/alda-lang/alda/releases
```

instead of 

```
Automated updates to alda.exe are not possible due to limitations of the Windows OS.
For more information, see: https://github.com/alda-lang/alda-client-java/issues/24

To update alda.exe, first, make sure that the server is not up by running:

   alda down

Then, run the following command in your terminal to download the latest alda.exe:

    powershell -Command Invoke-WebRequest -Uri "https://github.com/alda-lang/alda/releases/download/<version>/alda.exe" -OutFile "C:\Program Files (x86)\Alda\alda.exe"

Or, if you'd prefer, you can install the latest alda.exe yourself from:
https://github.com/alda-lang/alda/releases
```

?

**Comment by daveyarwood** [comment] 2018-12-03 18:57
@elyisgreat Does that only work when run in PowerShell?

If so, I'm still thinking that it might be best if we included 2 commands, one for cmd.exe and one for PowerShell.

On another note: that command is soooo long! [It looks like PowerShell supports breaking up input over multiple lines](https://stackoverflow.com/questions/3235850/how-to-enter-a-multi-line-command), so perhaps we can do something like this for better readability?

```powershell
    powershell `
        -Command {[Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Ssl3 `
        -bor [System.Net.SecurityProtocolType]::Tls `
        -bor [System.Net.SecurityProtocolType]::Tls12 ; `
        Invoke-WebRequest `
            -Uri "https://github.com/alda-lang/alda/releases/download/<version>/alda.exe" `
            -OutFile "C:\Program Files (x86)\Alda\alda.exe"}
```

**Comment by elydpg** [comment] 2018-12-03 19:02
Yea, but doesn't the old one have the same problem?

**Comment by daveyarwood** [comment] 2018-12-03 19:22
I don't think so. I think the existing one can be run in cmd.exe and it leverages `powershell` to do the thing. Take what I'm saying with a grain of salt because I don't have a Windows machine to test against, but I don't believe there is anything in the existing command that isn't valid syntax for cmd.exe.

**Comment by TBuc** [comment] 2018-12-04 16:02
@elyisgreat that one-liner looks great to me! Good job!

In July I did reach that solution too, sorry I didn't post it, but then got stuck at having it work from cmd.exe too - too high effort-to-improvement ratio job for my skills, so I gave up. That's a pity since most Windows users won't use Powershell.

@daveyarwood note that the line splitting will only work from native powershell - if you launch _powershell_ from _cmd.exe_ then launch the command it won't work instead.

**Comment by daveyarwood** [comment] 2018-12-04 16:53
Ah, that's a bummer. I guess we can't make it multi-line, then.

I'd still like to see a version that works for cmd.exe and a version that works for Powershell.

Is it the case that we could keep the current version as the one that works for cmd.exe, and use the new one @elyisgreat posted as the one that works for Powershell?

**Comment by TBuc** [comment] 2018-12-04 16:56
@daveyarwood AFAIK there's currently no version working on cmd.exe. Maybe I'm missing something?

**Comment by daveyarwood** [comment] 2018-12-04 17:13
Oh, I think I misunderstood!

So, I think what we should do, then, is to provide this new, improved version that works in Powershell, and make it clear that this will work if you're running Powershell, otherwise, you can manually download and install the latest release (which we're already including a link for).

**Comment by TBuc** [comment] 2018-12-05 17:27
Actually, keeping the single-line version proposed by @elyisgreat will work both when directly launching Powershell:
![image](https://user-images.githubusercontent.com/5067698/49531714-28177980-f8bb-11e8-98e8-80a13e2e16e1.png)
as much as when launching cmd.exe then therein invoking a powershell as follows:
![image](https://user-images.githubusercontent.com/5067698/49531480-a7587d80-f8ba-11e8-88e8-c4fd8705d47b.png)

The multi-line version of the same string will throw an error when launched from from the latter. For this reason, even thought the multi-line version is more readable, I'd suggest going for the single-line version.

But it's just my opinion on a presumably rare case, so if you decide to go for the multi-line version I will totally understand your point.

**Comment by daveyarwood** [comment] 2018-12-05 17:37
I'm fine with the single-line version. It sounds like the multi-line version is more trouble than it's worth.

If one of you would like to put together a PR, I'll happily merge it and include it with the next release of Alda!

**Comment by TBuc** [comment] 2018-12-18 10:39
PR submitted on that same day, sorry for forgetting to link it to this issue.

I've stumbled upon [Chocolatey](https://chocolatey.org/), a package manager for Windows. Looks like it's gaining a relevant user base (i.e., NodeJS installer will propose to install it too). This would add a layer, but would also enhance user experience.
Do you guys think we might rely on it for installing and updating Alda on Windows?

**Comment by daveyarwood** [comment] 2018-12-18 11:59
Chocolatey looks promising - definitely worth exploring for managing Alda updates on Windows. 

I'm not seeing a PR that makes the change we discussed above. Are you sure you submitted one?

**Comment by daveyarwood** [comment] 2021-01-01 21:01
I think I've figured out how to make `alda update` Just Work™ in Alda v2, even for Windows. If I'm understanding correctly, the issue on Windows is that you can't replace a program while it's running, but you _can_ rename it. So, I've read that there is this dance you can do where you rename the currently running executable, download the new version in its place, and then exit. Then, you have your program delete the old (renamed) versions on startup.

I'm planning to experiment with this and see if I can get it working in a Windows CI environment. If it works, the experience will be way better for Windows users.

I'm going to go ahead and close this issue, since it's Alda v1 specific and Alda v2 will be out soon :crossed_fingers:

**Closed as completed by daveyarwood** 2021-01-01 21:01 UTC
Labels: windows
