### ISSUE TITLE
alda demands Java which is actually there

### ISSUE THREAD

**Issue by jmizv** [alda-lang/alda-client-java#45] opened 2020-09-24 20:48 UTC
Whenever I try to start `alda` it opens a browser tab where I can download Java RE and prints the following message:

```
C:\Software>alda
This application requires a Java Runtime Environment 1.7.0
```

But there is some Java:
```
C:\Software>java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

Is the Java too new? What am I doing wrong here? I'm on Windows 10 Professional.

**Comment by daveyarwood** [comment] 2020-09-25 00:27
I think this might be a duplicate of #41 . There are a couple of ideas in that issue that you could try:

1. Try [this alternate build](https://github.com/alda-lang/alda-client-java/issues/41#issuecomment-529123378) of Alda where I've configured the JRE path differently. If it works, I can make that change to all Alda builds going forward.

2. Try installing the JRE as noted [in the last comment](https://github.com/alda-lang/alda-client-java/issues/41#issuecomment-560021396).

**Comment by daveyarwood** [comment] 2020-09-29 12:42
I'm closing this as a duplicate of https://github.com/alda-lang/alda-client-java/issues/41. We can always re-open it if this ends up being a different problem.

**Closed as completed by daveyarwood** 2020-09-29 12:42 UTC
Labels: windows
